### ISSUE TITLE
Weird stuff (unmocking might be broken) with Node.js 8

### ISSUE THREAD

**Issue by mightyiam** [boblauer/mock-require#24]
My reproduction code is [here](https://github.com/mightyiam/mock-path-with-simple-spy/tree/e7a363f2d437be0316d41b6ec8cf31db2e427aea).

Here is [a screencast of me debugging the issue](https://drive.google.com/file/d/0BxH2PmBUnzG4cGFMVDZYNm1JX0U/view?usp=sharing). I hope you enjoy it rather than swear at me for it.

So am I using it wrong or what?

**Comment by zakgrant** [comment]
I too am finding that with node 8 the mocks are not being reset on calling stop / stopAll

**Comment by boblauer** [comment]
@zakgrant Node 8 or 8.5?  I'm seeing a big difference between how `require` works internally from 8 to 8.5.

**Comment by zakgrant** [comment]
@boblauer yeah I am using node 8.5

**Comment by alexpchin** [comment]
I've got a similar issue... but I don't think it's with my version of node. I have something going on where some of the files stop mocking and some don't?

I use setup my mocks in a `spec_helper` file that gets loaded before running my express app, like so:

```js
mock('../../lib/docusign', '../../libmocks/docusign_mock');
```

and then in the test for the that specific lib file, I do:

```js
  before(() => {
    mock.stop('../../lib/docusign');
    docusign = require('../../lib/docusign');
  });

  after(() => {
    mock('../../lib/docusign', '../../libmocks/docusign_mock');
  });
```

With the goal of mocking with fixtures for everything apart from testing the file itself.
It seems to work with some of the lib files but not others?

**Comment by robertmain** [comment]
Not sure if it's related or not, but I'm finding that it's not catching module `import` statements if I `import * as fs from 'fs'`. Is it supposed to work with `import` as well?

**Comment by boblauer** [comment]
@alexpchin I think you're right that that is unrelated.  Do you mind opening a new issue, with possibly a sample project that reproduces the issue?

@robertmain It does not work with native `import` statements.  If your code is being transpiled by babel, for example, then it should work, because those `import` statements actually get converted to `require` statements.  However, it's a bit more complex than that.

I would recommend you take a look at https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=Q&debug=false&circleciRepo=&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&targets=&version=6.26.0 to see what your code is actually being converted to, I suspect the issue might be in the conversion itself.

**Comment by robertmain** [comment]
Well my code is TypeScript so, it is running through a transpiler(just not Babel). However it seems not to be working with that.

**Comment by bobbyg603** [comment]
I'm also having this issue in node 8.5 :/. Anyone have a workaround?

**Comment by robertmain** [comment]
@bobbyg603 I ended up using a different package(`mock-fs`) instead`

**Comment by mightyiam** [comment]
This is still an issue with latest version, `3.0.1`.
https://travis-ci.org/mightyiam/mock-path-with-simple-spy/jobs/328199961#L1872

**Comment by mightyiam** [comment]
Still an issue. See failing CI here:
https://github.com/mightyiam/mock-path-with-simple-spy/pull/29

**Comment by patrick99e99** [comment]
Still an issue for me as well...
