### ISSUE TITLE
Impossible to return strings

### ISSUE THREAD

**Issue by Owlbertz** [boblauer/mock-require#28]
Hi,
I am currently having the issue where I want to mock a HTML-file. Unfortunately, I cannot do this because if the second argument of `mock()` is a string, it assumes that it is a path to look for a module to return. But I simply want `mock('../templates/template.html', 'dummytemplate')` to return `'dummytemplate'`.
Maybe this is already possible somehow...?

**Comment by boblauer** [comment]
This is not possible currently, as you are correct that it assumes a string is a file path.

I would suggest making a `dummy-template.html` file instead.

**Comment by Owlbertz** [comment]
Having a dummy template is what I am currently doing, but as my project has a rather dynamic structure, this leads to issues during building and testing (using gulp), as files get copied to different locations.

**Comment by boblauer** [comment]
Unfortunately I don't think this would be a good feature to add, as it would hide errors when referencing an incorrect path/module.  For example, `mock('./file.js', './otherr-file.js')` would "return" the string `./otherr-file.js`, rather than alerting the user that `./otherr-file.js` does not exist.

Depending on how your code is setup, you might be able to get away with doing something like:

```js
const html = {
  toString: () => '<html />'
};

mock('./template.html', html);
```

`require('./template.html')` will now return an object, but if that object is coerced into a string later on, then it will work just as if it were a string.  It's a bit of a hack, but it may work for you depending on how this html string is being used later on in the code.

**Comment by Owlbertz** [comment]
I actually tried that, but it failed as `toString()` was not invoked in my case.
I guess I will just find a way to copy the templates to where they are searched as well.
